### ISSUE TITLE
Not working anymore with Sentry 8.5.1 ?

### ISSUE THREAD

**Issue by sbadia** [educreations/sentry-sso-google#12]
Hi here!

I'm trying to configure `sentry-sso-google`, with sentry `8.5.1`, but the « Google » auth method never appear in `Manage > Auth > Provider` (`No authentication providers are available.`)

In my configuration (`sentry.conf.py`) I have this:

```python
INSTALLED_APPS + ('sentry_sso_google',)
GOOGLE_OAUTH2_CLIENT_ID = environ.get('GOOGLE_OAUTH2_CLIENT_ID')
GOOGLE_OAUTH2_CLIENT_SECRET = environ.get('GOOGLE_OAUTH2_CLIENT_SECRET')
GOOGLE_WHITE_LISTED_DOMAINS = ['mydomain.com']
```

(env var are correctly configured ;-))

A clue?

Thanks in advance!

**Comment by streeter** [comment]
Was it working before Sentry 8.5 for you? Or did 8.5 cause it to stop working?

**Comment by sbadia** [comment]
Hum I don't know, I just tested with a new installation using the latest sentry version.

**Comment by meastman** [comment]
> `INSTALLED_APPS + ('sentry_sso_google',)`

I think you want `+=` here.

**Comment by streeter** [comment]
Good catch @meastman!

@sbadia, that will probably affect your configuration, as `sentry_sso_google` won't get pulled in by Django.

Let me know if you try that and it does not work with Sentry 8.5+

**Comment by sbadia** [comment]
Indeed, it's the issue! Thanks! :)
