### ISSUE TITLE
Documentation issue: needed to enable Google+ APIs in developer console

### ISSUE THREAD

**Issue by DominicWatson** [educreations/sentry-sso-google#7]
Setup failed until I enabled "Google+ API" in the developer console for the App I created for SSO authentication.

By "failed", I mean that I'd receive an Internal Error after signing into Google and being redirected back to Sentry during the SSO *configuration* process. Digging into it showed that it was a 403 response to a request to the google plus address for getting user profile data.

Not sure if this is expected, but if it is, would be worth documenting it here.

**Comment by meastman** [comment]
Thanks for pointing this out. It's expected, and I've opened a PR to update the documentation.

**Comment by streeter** [comment]
@DominicWatson there's a new release out that documents the requirement: https://pypi.python.org/pypi/sentry-sso-google

Thanks for the report!

**Comment by DominicWatson** [comment]
Awesome :)
